site_name: AiDraw
site_description: 一个介绍 Ai 绘画的 WIKI/A WIKI about Ai painting
site_url: 'https://stable-diffusion-book.vercel.app/'
site_author: StableDiffusionBook Team
repo_url: 'https://github.com/sudoskys/StableDiffusionBook'
edit_uri: edit/main/docs/
copyright: |
  Copyright &copy; 采用 GFDL 协议

theme:
  name: material
  language: zh
  icon:
    logo: material/brush
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections


markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.superfences
  - meta
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/s/StableDiffusion_CN_WIKI'
    #- icom: fontawesome/brands/discord
    #  link: 'https://discord.gg/vhsArSSA6K'
  generator: true


nav:
  - 起步于此:
      - index.md
      - 新闻: GettingStarted/news.md
      - 术语: GettingStarted/term.md
      - 声明: GettingStarted/state.md
      - 贡献指南: GettingStarted/contributing.md
  - 开始之前:
      - prepare/index.md
  - 安装配置:
      - install/index.md
      - WebUi安装:
          - 运行WebUi: install/WebUi/launch.md
          - 错误处理: install/WebUi/Troubleshoot.md
  - 调试程序:
      - config/index.md
      - GPU相关: config/GPU.md
  - 绘画指南:
      - 概论: 
          - paint/index.md
          - 提示工程: paint/PromptsEngineering.md
      - 工作流:
          - paint/WebUi/index.md
          - Txt2模式: paint/WebUi/base.md
          - Img2模式: paint/WebUi/Advanced.md
          - 姿态骨架: paint/WebUi/Control.md
      - 实战指南:
          - paint/Practicalguide.md
          - 评估: paint/identify.md
  - 训练模型:
      - 训练介绍: train/index.md
      - Textual 训练: train/Textual.md
      - Hypernetwork 训练: train/Hypernetwork.md
      - Lora 训练: train/Lora.md
      - DreamBooth 训练: train/DreamBooth.md
      - AestheticGradients 训练: train/AestheticGradients.md
  - 参考资料:
      - landing/index.md
      - 资料表: landing/link.md


plugins:
  - glightbox
  - search
  - social:
      cards_font: Noto Sans SC
      cards_color:
        fill: '#D8C7B5'
        text: '#492D22'
  - i18n:
      material_alternate: true
      default_language: zh
      nav_translations:
        en:
          起步于此: Start here
          术语: Terminology
          新闻: News
          声明: Statement
          开始之前: Before start
          安装配置: Installation
          WebUi安装: Install SDWebUi
          绘画调试: Configuration
          GPU相关: Gpu Debuging
          NAI泄漏报告: NAI leak report
          WebUi配置模型: Configrue Model for WebUi
          绘画指南: Paint guide
          Txt2指南: Txt2Guide
          Img2指南: Img2Guide
          基本指南: Base guide
          WebUi绘画指南: Paint With WebUi
          实战指南: Application Guide
          进阶指南: Advanced Guide
          安装扩展: Extension
          训练模型: Train Model
          训练介绍: Intro
          Textual 训练: Textual Inversion
          Hypernetwork 训练: Hypernetwork
          DreamBooth 训练: DreamBooth
          Lora 训练: Lora
          AestheticGradients 训练: AestheticGradients
          参考资料: References
          运行WebUi: LaunchWebUi
          错误处理: Troubleshoot
          工作台: Workstations
          贡献指南: Contribution Guide
          概论: General
          鉴别: Identify
          提示工程: Prompts Engineer
          资料表: Resource List
      languages:
        en:
          name: English
        zh:
          name: 简体中文
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
