name: Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Picture Support
      - run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev

      - uses: actions/cache@v2
        with:
            key: ${{ github.ref }}+20221107
            path: .cache
            
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Dependence
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-glightbox 

      # Picture Support
      - run: pip install pillow cairosvg
      
      - name: Build
        run: mkdocs build --clean
      # - run: mkdocs gh-deploy --force

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          # cname: example.com # if wanna deploy to custom domain
